[package]
name = "math_vector"
version = "0.1.0"
edition = "2021"
description = "My package for aimbot calculations / vector math"
repository = "https://github.com/thedraculaisreal/vector_math"

[dependencies]
libm = "0.2.11"
